version: "0.1"

services:
  spark-master:
    image: apache/spark:3.5.1
    container_name: spark-master
    hostname: spark-master
    #container-name You see this when running local terminal commands like docker ps or when clicking through your Docker Desktop App UI.
    #hostname You see this if you log into the worker container's terminal and run the hostname command, or inside Spark's network management logs.
    command: >
      bash -c "
      /opt/spark/sbin/start-master.sh &&                                    
      tail -f /opt/spark/logs/spark--org.apache.spark.deploy.master*.out
      "
    # bash -c: Executes the string inside the quotes as a Bash shell command.
    #tail -f: Displays a log file on your screen and updates live as new rows appear.
    #/opt/spark/sbin/start-master.sh: This is the command to start the Spark Master node.
    #The && operator ensures that the tail command runs only after the master has started successfully.
    #"" is for Groups the separate lines of code into a single text block. for -c
    #The log file being tailed is the one generated by the Spark Master process, which 
        #contains important information about the status and activities of the master node.
    # The * is a wildcard character used because you do not know the exact name of the log file ahead of time.
    #spark-[username]-org.apache.spark.deploy.master.Master-[instance]-[hostname].out    The * tells the system to
        # match any text that fills in those blanks, allowing the command to successfully find and open the log file regardless of
        # your current username, computer hostname, or background process ID.
        #because log filenames using dynamic information that changes every time the system boots 
    ports:
      - "8080:8080"   # Spark Master UI
      - "7077:7077"   # Spark Master port
    #- "7070:7077": Opens the Spark Master port, which is used for communication between the master and worker nodes in the cluster.
    # "localhost port:inernal container" ->"port1:port2"
    volumes:
      - ./app:/opt/spark-app  
      - ./data:/opt/spark-data
    #The app folder is for your logic (the instructions)[.py,.java], 
    #while the data folder is for your inputs/outputs (the information being processed)[csv, .json, .parquet, or .txt.].
    #logs are stored inside the container, so you won't see them on your physical laptop{not in app or data}.
      
#here we define spark-worker-1 as a worker +drivr too[u can create seperte driver too]
  spark-worker-1:
    image: apache/spark:3.5.1
    container_name: spark-worker-1
    hostname: spark-worker-1
    environment:
      SPARK_PUBLIC_DNS: localhost #This environment variable is used to set the public DNS name for the Spark Worker node.
    command: >
      bash -c "/opt/spark/sbin/start-worker.sh spark://spark-master:7077 --cores 2 --memory 2g &&
      tail -f /opt/spark/logs/spark--org.apache.spark.deploy.worker*.out"
    ports:
      - "8081:8081"
      - "4040:4040"
    # - "8081:8081": Opens the Spark Worker Web UI, allowing you to view its status by typing http://localhost:8081 into your browser.
    # - "4040:4040": Opens the Spark Application UI port, which tracks the live progress of individual data jobs you submit to the cluster.
    depends_on:
      - spark-master
    volumes:
      - ./app:/opt/spark-app
      - ./data:/opt/spark-data
  #/opt/spark/sbin/start-worker.sh  The absolute file path to Spark's official worker startup script.
  #spark://spark-master:7077   spark:// is the protocol, spark-master is the container/host name, 
      #and 7077 is the default port Spark masters use to communicate with workers.
  #--cores 2 It strictly limits this specific worker node to use a maximum of 2 CPU cores for processing data.
  #--memory 2g It restricts this worker node to use a maximum of 2 Gigabytes (2g) of RAM.
  spark-worker-2:
    image: apache/spark:3.5.1
    container_name: spark-worker-2
    hostname: spark-worker-2
    environment:
      SPARK_PUBLIC_DNS: localhost #This environment variable is used to set the public DNS name for the Spark Worker node.
    command: >
      bash -c "/opt/spark/sbin/start-worker.sh spark://spark-master:7077 --cores 2 --memory 2g &&
      tail -f /opt/spark/logs/spark--org.apache.spark.deploy.worker*.out"
    ports:
      - "8082:8081"
      #- "4041:4040"  
      # do not need this as this is just a worker and not driver no need to track live progress of individual data jobs you submit to the cluster.
    depends_on:
      - spark-master
    volumes:
      - ./app:/opt/spark-app
      - ./data:/opt/spark-data
#why is the rigght port can be same but we have,have,have to change the left port "port1:port2"
#Each container is its own independent mini-computer.Worker 1 has its own isolated operating system. 
    #Inside its walls, Spark runs on port 4040.Worker 2 has its own separate isolated operating system.
    # Inside its walls, Spark also runs on port 4040.
#The left port belongs to your actual physical laptop. Your laptop only has one single port 4040.causing conflict if same port in physical